spring:
  datasource:
    url: jdbc:mysql://mysql:3306/clinic
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    # You can also specify dialect if needed:
    # database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
